spring:
  mvc:
    static-path-pattern: /static/**
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1
  port: 8080

jwt:
  private-key-path: ./keys/private_key.pem
  public-key-path: ./keys/public_key.pem
